name: "Integration Testing"

on: [pull_request]

jobs:
  Integration:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platforms:
          - centos-7
        pe_version:
          - 2021.7.5
          - 2023.4.0

    env:
      PUPPET_GEM_VERSION: '~> 7.24'

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Activate Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true

    - name: Print bundle environment
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::
    - name: Create the fixtures directory
      run: |
        echo ::group::Create the fixtures directory
        bundle exec rake spec_prep
        echo ::endgroup::
    - name: Provision test environment
      run: |
        bundle exec bolt --modulepath spec/fixtures/modules plan run pe_event_forwarding::acceptance::provision_machines using='provision_service' image='${{ matrix.platforms }}'
        echo ::group::=== REQUEST ===
        cat request.json || true
        echo
        echo ::endgroup::
        echo ::group::=== INVENTORY ===
        if [ -f 'spec/fixtures/litmus_inventory.yaml' ];
        then
          FILE='spec/fixtures/litmus_inventory.yaml'
        elif [ -f 'inventory.yaml' ];
        then
          FILE='inventory.yaml'
        fi
        sed -e 's/password: .*/password: "[redacted]"/' < $FILE || true
        echo ::endgroup::
        echo INVENTORY_PATH=$FILE >> $GITHUB_ENV
    - name: Install server
      run: |
        bundle exec bolt --modulepath spec/fixtures/modules plan run pe_event_forwarding::acceptance::pe_server version='${{ matrix.pe_version }}' -i ./$INVENTORY_PATH --stream
    - name: Add localhost target to inventory
      run: |
        bundle exec rake 'acceptance:add_localhost_target'
    - name: Install module
      run: |
        bundle exec rake 'litmus:install_module'
    - name: Run acceptance tests
      run: |
        bundle exec rake acceptance:run_tests
    - name: Remove test environment
      if: ${{ always() }}
      continue-on-error: true
      run: |
        if [[ -f inventory.yaml || -f spec/fixtures/litmus_inventory.yaml ]]; then
          bundle exec rake 'litmus:tear_down'
          echo ::group::=== REQUEST ===
          cat request.json || true
          echo
          echo ::endgroup::
        fi
